export const ErrorCode = {
  // AUTH ERRORS
  BASE_URL_MISSING: 'BASE_URL_MISSING',
  CLIENT_ID_MISSING: 'CLIENT_ID_MISSING',
  CLIENT_SECRET_MISSING: 'CLIENT_SECRET_MISSING',
  ACCESS_TOKEN_MISSING: 'ACCESS_TOKEN_MISSING',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  ERROR_REFRESHING_ACCESS_TOKEN: 'ERROR_REFRESHING_ACCESS_TOKEN',
  REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // CLIENT ERRORS
  CONN_ERROR: "CONN_ERROR",
  CLIENT_CONFIGURATION_ERROR: 'CLIENT_CONFIGURATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // USER ERRORS
  USER_ID_INVALID: 'USER_ID_INVALID',
};

export class ApiError extends Error {
  constructor(message, code, originalError = null) {
    super(message);
    this.name = 'ApiError';
    this.code = code; // ErrorCode
    this.originalError = originalError;
  }
}